### ISSUE TITLE
ЛР

### ISSUE THREAD

**Issue by TonitaN** [geogreck/ics9-tfl#1]
Результат на конфиге
```
n: 2
word: g(g(t,t),h(t))
rules: |
  g(x,x) -> h(x)
  h(t) -> f
```
равен `[g(f,h(t))]`. А там их должно быть больше...

И ещё нет поля `variables`, поэтому непонятно, можно ли подставлять внутрь `x` и `t` другие значения, или нужно рассматривать их как константы.

**Comment by TonitaN** [comment]
Ну и то, что сейчас в юнит-тестах, трудно назвать "сложными" тестами (максимум - переименовка). Не расстраивайте стихию, сделайте несколько нормальных тестов на переписывание, перепроверив их руками.

**Comment by geogreck** [comment]
Про variables если честно, не понял( Если для x правил нет, то, кажется, внутрь него ничего и не поставить

**Comment by TonitaN** [comment]
В ЛР 1 вариантов 2, 4, 5 есть такая графа `variables`. Она нужна, чтобы понять, является ли символ контейнером или константой. Например, если так:
```
variables: x
word: g(h(x),h(x))
rules: |
  g(x,x) -> h(x)
```
то слово в `h(h(x))` перепишется, потому что унификация с левой частью правила породит подстановку `x:=h(x)`. А если так:
```
variables: y
word: g(h(x),h(x))
rules: |
  g(x,x) -> h(x)
```
То `x` посчитается константой, а подслова `g(x,x)` во входном слове нет, поэтому ничего никуда не перепишется.
Если всё ещё непонятно, то призовите в консультанты кого-нибудь, кто делал ЛР 1 вариант 2,4,5, например @viacheslavek.

**Comment by geogreck** [comment]
Занимательно, спасибо!

**Comment by IOANNVOLZHSKIY** [comment]
> Занимательно, спасибо!

Действительно, было бы неплохо спросить Вячеслава про ЛР

**Comment by geogreck** [comment]
Выглядит как починенная лаба для меня, интересно узнать, почему это не так (готов к проверке)

**Comment by TonitaN** [comment]
Выглядит, как ловушка Славы (или немножко внезапного рефал-стиля?). См. вход:
```
n: 2
variables: [x, t]
word: g(g(g(f(z))))
rules: |
  g(f(z)) -> g(f(z))
```
Ответ - пустое множество почему-то, хотя казалось бы константа должна переписываться в себя. Я даже догадываюсь, почему)

**Comment by geogreck** [comment]
Слава отказался признавать, что это его ловушка, придется самому чинить

**Comment by geogreck** [comment]
Стоя в очереди в деканат, работается гораздо лучше, фикс готов!

**Comment by geogreck** [comment]
Совершил ужасный грех и запушил неправильные тесты. Чтобы такого больше не было, добавил запуск тестов в ci

**Comment by TonitaN** [comment]
Надеюсь, ваша очередь в деканат уже закончилась, т.к. фиксить больше тут нечего.

**Comment by geogreck** [comment]
Прием в деканате ещё даже не начался, просто подготовка к марафону по тфя включает в себя вставание в очередь у деканата за полтара часа до начала приема (@IOANNVOLZHSKIY и @t1d333 не дадут соврать). 

А по первому рк ещё остались какие-то вопросы?, а то я не совсем понял...

**Comment by TonitaN** [comment]
Те, что остались, приберегу на компромат. А @t1d333 и сам не эксперт (и уже не станет им) в вопросах очереди в деканат по поводу тфя, тут нужно призывать в свидетели более опытных дедлайнеров.

**Comment by geogreck** [comment]
Большое спасибо! Теперь на полной уверенности могу брать направление на сдачу. А Кирилла жалко, он так хотел стать TA в следующем году, помогая Ваня и Леше

**Comment by TonitaN** [comment]
> Большое спасибо! Теперь на полной уверенности могу брать направление на сдачу. А Кирилла жалко, он так хотел стать TA в следующем году, помогая Ваня и Леше

Ну это ещё не поздно, но для этого достаточно делать мотивирующие ревью в чужих репозиториях по тфя и курсовым по тфя, что никак не связано с очередями в деканат, и даже с решением задач по тфя самолично, как доказал ваш опыт.

**Comment by geogreck** [comment]
Ура...

**Comment by TonitaN** [comment]
Не слишком радостное ура у вас...

**Comment by geogreck** [comment]
Вчера я увидел слишком много академических смертей

**Comment by geogreck** [comment]
Да и как теперь жить без тфя
